[package]
name = "greydio-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
serde_json = { workspace = true }
greydio-crypto = { path = "../crypto" }
greydio-types = { path = "../types" }
hex = { workspace = true }
