[package]
name = "greydio-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
blake3 = { workspace = true }
bincode = { workspace = true }
anyhow = { workspace = true }
